### ISSUE TITLE
[info] Is Cross-Lib doing what you need?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [seanwiththebeard/XINAGA#1]
I saw you starred my Cross-Lib project: https://github.com/Fabrizio-Caruso/CROSS-LIB

If it does most of what you want to do with XINAGA, let me know if you want to give it a try. Feel free to ask me for help on how to use it. Cross-Lib is not perfect. It is a huge one-man project. 

Cross-Lib is:
(1) A universal C library for about 200 retro systems across several architectures, you write your code *once* and then you can compile it with a dozen different cross-compilers to get the same game. You can even compile it natively for the PC (terminal only for the moment). You do not need to write target-specific code. Even graphics assets (tiles) are shared whenever possible.
(2) A set of tools to import, export, manage graphics assets.
(3) A set of tools to build, create projects, manage projects.

Cross-Lib is NOT a compiler, though. You use it with cross-compilers (or native compilers).

Remark:
- Graphics is only tile-based as this is the only possible graphics on all targets including ASCII-only ones. Target with real graphics can use tiles with defined shapes. ASCII-only targets with no graphics can only map tiles to ASCII shapes.
- Sounds are even more limited: just some sound effects.
- Input is either IJKL SPACE or joystick.
- No interrupt as not only targets have interrupts
- Speed can be tune on each target by setting a specific variable in its Makefile.

I will improve Cross-Lib in the future but I won't add features that would prevent it from being universal.

**Comment by seanwiththebeard** [comment]
It's definitely very similar! I actually figured out how to implement my preprocessor conditions after looking at some of your code. My big project is an Ultima clone for C64 and Apple II, but I started realizing how much of my drawing code needs to be abstracted out for multiple platforms. If I had seen Cross-Lib earlier I probably would have started with it, but part of the fun has been learning how to implement the same things on the different platforms. I'll definitely be checking out some of the graphics tools from Cross-Lib moving forward.

The next things I'm thinking about are implementing my 2x2 tilemap system as well as multiple "draw targets" for movable windows.
